In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

with open(
    "SENSEX Top Gainers, BSE Daily Top Gainers - Stock Market.html",
    "r",
    encoding="utf-8",
) as file:
    response = file.read()
    soup = BeautifulSoup(response, "html.parser")
    # print(soup.prettify())
    articles = soup.find_all("tr")
    frame = []
    for a in articles:
        try:
            Company = a.find("td", class_="v-align").text.strip()
            Current_Price = a.find("td", class_="txt-right v-align").text.strip()
            Prev_Close_Date = a.find("td", class_="txt-right no-wrap").text.strip()
            Change = a.find("td", class_="txt-ctr").text.strip()
            Change_Percent = a.find("span", class_="green-btn").text.strip()
            day_low = a.find("span", class_="fl f-9").text.strip()
            day_high = a.find("span", class_="fr f-9").text.strip()
        except AttributeError:
            continue

        frame.append(
            (
                Company,
                Current_Price,
                Prev_Close_Date,
                Change,
                Change_Percent,
                day_low,
                day_high,
            )
        )

df = pd.DataFrame(
    frame,
    columns=[
        "Company",
        "Current Price",
        "Prev Close Date",
        "Change",
        "Change Percent(%)",
        "Day Low",
        "Day High",
    ],
)
df
# df.to_csv("SENSEX_Top_Gainers.csv", index=False)

,Company,Current Price,Prev Close Date,Change,Change Percent(%),Day Low,Day High
0,Tata Motors,583.30,569.55\n16-06-2023,13.75,13.75,562.40,584.00
1,HCL Tech.,1168.20,1149.00\n16-06-2023,19.20,19.20,1130.15,1170.00
2,TCS,3227.20,3175.25\n16-06-2023,51.95,51.95,3201.60,3232.00
3,Power Grid Corpn.,248.95,246.10\n16-06-2023,2.85,2.85,243.25,249.75
4,Infosys,1303.15,1292.65\n16-06-2023,10.50,10.50,1291.00,1304.40
5,Vedanta,282.60,280.35\n16-06-2023,2.25,2.25,278.70,284.35
6,Larsen & Toubro,2382.20,2366.50\n16-06-2023,15.70,15.70,2355.00,2390.30
7,Bajaj Finance,7247.85,7203.40\n16-06-2023,44.45,44.45,7202.00,7375.00
8,HDFC Bank,1608.30,1602.10\n16-06-2023,6.20,6.20,1590.90,1610.95
9,Bajaj Auto,4659.90,4642.75\n16-06-2023,17.15,17.15,4570.70,4670.80
10,HDFC,2657.85,2651.15\n16-06-2023,6.70,6.70,2632.00,2663.25
11,ONGC,157.25,156.90\n16-06-2023,0.35,0.35,156.60,157.80
12,Asian Paints,3318.40,3315.20\n16-06-2023,3.20,3.20,3276.30,3326.45
13,Tata Steel,114.30,114.25\n16-06-2023,0.05,0.05,113.50,115.25

In [4]:
import pandas as pd
h=pd.read_html("SENSEX Top Gainers, BSE Daily Top Gainers - Stock Market.html")
h[0]

,Company,Current Price,Prev Close Date,Change,Change %,Day's Low/High
0,Tata Motors,583.30,569.55 16-06-2023,13.75,2.41%,562.40 584.00
1,HCL Tech.,1168.20,1149.00 16-06-2023,19.20,1.67%,1130.15 1170.00
2,TCS,3227.20,3175.25 16-06-2023,51.95,1.64%,3201.60 3232.00
3,Power Grid Corpn.,248.95,246.10 16-06-2023,2.85,1.16%,243.25 249.75
4,Infosys,1303.15,1292.65 16-06-2023,10.50,0.81%,1291.00 1304.40
5,Vedanta,282.60,280.35 16-06-2023,2.25,0.80%,278.70 284.35
6,Larsen & Toubro,2382.20,2366.50 16-06-2023,15.70,0.66%,2355.00 2390.30
7,Bajaj Finance,7247.85,7203.40 16-06-2023,44.45,0.62%,7202.00 7375.00
8,HDFC Bank,1608.30,1602.10 16-06-2023,6.20,0.39%,1590.90 1610.95
9,Bajaj Auto,4659.90,4642.75 16-06-2023,17.15,0.37%,4570.70 4670.80
10,HDFC,2657.85,2651.15 16-06-2023,6.70,0.25%,2632.00 2663.25
11,ONGC,157.25,156.90 16-06-2023,0.35,0.22%,156.60 157.80
12,Asian Paints,3318.40,3315.20 16-06-2023,3.20,0.10%,3276.30 3326.45
13,Tata Steel,114.30,114.25 16-06-2023,0.05,0.04%,113.50 115.25